# Generated by Django 4.1.5 on 2023-01-07 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_email', models.EmailField(max_length=255, null=True)),
                ('comment_description', models.TextField()),
                ('comment_likes', models.IntegerField(default=0)),
                ('comment_dislikes', models.IntegerField(default=0)),
                ('comment_date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
