# Generated by Django 4.1.5 on 2023-01-07 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('ingredient_quantity', models.CharField(blank=True, max_length=255)),
                ('ingredient_date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
