# Generated by Django 4.1.5 on 2023-01-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_main_photo',
            field=models.FileField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_photo1',
            field=models.FileField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_photo2',
            field=models.FileField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_photo3',
            field=models.FileField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
